### ISSUE TITLE
Feature Request: override default behavior in context menu.

### ISSUE THREAD

**Issue by bryanbraun** [olmokramer/atom-pane-split-moves-tab#1]
First, this is nice, simple little plugin. Great work. :star2: 

I was thinking, it would be nice if it overrode the default behavior in Atom's context menus as well. For example, when right-clicking on a tab:

![image](https://cloud.githubusercontent.com/assets/1256329/9766513/4a69fc70-56e7-11e5-98e6-96bb32fab877.png)

**Comment by olmokramer** [comment]
It should already do that from the context menu on the editor, but I can confirm it doesn't work on the tabs. I'll see what I can do about that.

**Comment by bryanbraun** [comment]
:+1:

**Comment by olmokramer** [comment]
Hey, I've just published an update with the requested feature included. Could you please let me know if it's working alright?

**Comment by bryanbraun** [comment]
Confirmed, it works like a charm!

:sparkles: Thanks! :sparkles:

**Comment by olmokramer** [comment]
You're welcome :)
