### ISSUE TITLE
Not working in Atom 1.6.0

### ISSUE THREAD

**Issue by levity** [olmokramer/atom-pane-split-moves-tab#3]
I upgraded to Atom 1.6.0 and this package no longer seems to behave as expected. Even when it's enabled, pane splitting still leaves the file in the old pane.

**Comment by BenjaminConant** [comment]
I am also have this issue

**Comment by olmokramer** [comment]
Thanks for the report! While trying to fix this I found that Atom now has this functionality built-in with the command `pane:split-<direction>-and-move-active-item`, so you can override the keybinding with that command.

`tab:split-<direction>` still copies the active pane item, so the package still overrides those commands to remove the previous active item. They were also broken, but that is fixed now :)

**Comment by jamesplease** [comment]
> Thanks for the report! While trying to fix this I found that Atom now has this functionality built-in with the command pane:split-<direction>-and-move-active-item, so you can override the keybinding with that command.

Oh, nice. Good find!
